#!/data/data/com.termux/files/usr/bin/bash
# ╔══════════════════════════════════════════════════════════╗
# ║        TERMUX BANNER TOOL v2.0 - MAIN INSTALLER          ║
# ║        35 banner styles • 35 prompts • 10 themes         ║
# ╚══════════════════════════════════════════════════════════╝

# ---- UI colors (installer only) ----
IR='\e[1;31m'; IG='\e[1;32m'; IY='\e[1;33m'
IB='\e[1;34m'; IM='\e[1;35m'; IC='\e[1;36m'
IW='\e[1;37m'; IN='\e[0m'

# ---- Paths ----
REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TOOL_DIR="$HOME/.termux-banner-tool"
BACKUP_DIR="$TOOL_DIR/backups"
CONFIG_FILE="$TOOL_DIR/config"
BANNER_OUT="$TOOL_DIR/banner.sh"

# ---- Load libraries ----
for lib in banners.sh prompts.sh colors.sh; do
  if [[ ! -f "$REPO_DIR/$lib" ]]; then
    echo -e "${IR}Error: missing library $lib. Run from the repo folder.${IN}"
    echo -e "${IY}Usage: bash install.sh${IN}"
    exit 1
  fi
  # shellcheck disable=SC1090
  source "$REPO_DIR/$lib"
done

mkdir -p "$TOOL_DIR" "$BACKUP_DIR"

# ═══════════════ Config ═══════════════
cfg_get() { grep -E "^$1=" "$CONFIG_FILE" 2>/dev/null | cut -d= -f2-; }
cfg_set() {
  local k="$1" v="$2" tmp="$CONFIG_FILE.tmp"
  grep -vE "^$k=" "$CONFIG_FILE" 2>/dev/null > "$tmp" || true
  echo "$k=$v" >> "$tmp"
  mv "$tmp" "$CONFIG_FILE"
}

init_config() {
  [[ -f "$CONFIG_FILE" ]] && return 0
  cfg_set "NAME" "Khandakar"
  cfg_set "BANNER" "Slant Hacker"
  cfg_set "PROMPT" "FPV Arrow"
  cfg_set "THEME" "Ocean 🌊"
}

# ═══════════════ Dependencies ═══════════════
check_deps() {
  local missing=()
  command -v figlet >/dev/null 2>&1 || missing+=("figlet")
  command -v toilet >/dev/null 2>&1 || missing+=("toilet")
  if ((${#missing[@]} > 0)); then
    echo -e "${IY}Installing required packages: ${missing[*]} ...${IN}"
    pkg install -y "${missing[@]}"
  fi
}

# ═══════════════ Theme helpers ═══════════════
# Splits THEME_COLORS[name] ("c1|c2|c3") into global array TC[]
load_theme() {
  local theme="$1"
  local spec="${THEME_COLORS[$theme]:-${THEME_COLORS["Ocean 🌊"]}}"
  IFS='|' read -r -a TC <<< "$spec"
}

# ═══════════════ Logo renderer (build time) ═══════════════
# Renders logo art lines into global array LOGO[] using figlet/toilet.
# Falls back to plain name if renderer/font is missing.
render_logo() {
  local name="$1" style="$2"
  LOGO=()
  local spec="${BANNER_FONT[$style]:-figlet:slant}"
  local renderer="${spec%%:*}"
  local font="${spec#*:}"
  local art="" ok=0

  if [[ "$renderer" == "figlet" ]] && command -v figlet >/dev/null 2>&1; then
    if art="$(figlet -f "$font" -w 200 "$name" 2>/dev/null)" && [[ -n "$art" ]]; then ok=1; fi
  elif [[ "$renderer" == "toilet" ]] && command -v toilet >/dev/null 2>&1; then
    if art="$(toilet -f "$font" "$name" 2>/dev/null)" && [[ -n "$art" ]]; then ok=1; fi
  fi

  if ((ok == 0)); then
    if command -v figlet >/dev/null 2>&1 && art="$(figlet -f standard -w 200 "$name" 2>/dev/null)"; then
      :
    else
      art="$name"
    fi
  fi

  while IFS= read -r line; do LOGO+=("$line"); done <<< "$art"
  # Drop trailing empty lines
  while ((${#LOGO[@]} > 0)) && [[ -z "${LOGO[-1]// }" ]]; do unset 'LOGO[-1]'; done
}

logo_width() {
  local w=0 line len
  for line in "${LOGO[@]}"; do
    len=${#line}
    ((len > w)) && w=$len
  done
  echo "$w"
}

# ═══════════════ Banner builder ═══════════════
build_banner() {
  local name banner theme
  name="$(cfg_get NAME)";   [[ -z "$name" ]] && name="Khandakar"
  banner="$(cfg_get BANNER)"; [[ -z "$banner" ]] && banner="Slant Hacker"
  theme="$(cfg_get THEME)";  [[ -z "$theme" ]] && theme="Ocean 🌊"

  load_theme "$theme"
  local ncols=${#TC[@]}
  # Escape display name for safe embedding in the generated script
  local sname="${name//\'/\'\\\'\'}"
  local dname="$name"
  dname="${dname//\\/\\\\}"
  dname="${dname//\"/\\\"}"
  dname="${dname//\$/\\\$}"
  dname="${dname//\`/\\\`}"
  local frame="${BANNER_FRAME[$banner]:-none}"

  render_logo "$name" "$banner"
  local width
  width=$(logo_width)

  {
    echo "#!/data/data/com.termux/files/usr/bin/bash"
    echo "# Generated by Termux Banner Tool - $banner / $theme"
    echo "clear"
    echo "W='\\e[1;37m'; N='\\e[0m'"
    echo ""
    # Welcome header
    echo "echo -e '${TC[0]}╔══════════════════════════════════════════════════════════╗${N}'"
    echo "echo -e '${TC[1]}║${W}     ★  W E L C O M E   T O   T E R M U X  ★${TC[1]}               ║${N}'"
    echo "echo -e '${TC[2 % ncols]}╚══════════════════════════════════════════════════════════╝${N}'"
    echo "echo \"\""
    # Top frame
    if [[ "$frame" == "line" ]]; then
      printf "echo -e '"
      printf '%s' "${TC[1]}"
      printf "%${width}s" "" | tr ' ' '─'
      printf "%s'\n" "$N"
    elif [[ "$frame" == "stars" ]]; then
      printf "echo -e '"
      printf '%s' "${TC[1]}"
      local i; for ((i = 0; i < width; i += 2)); do printf '★ '; done
      printf "%s'\n" "$N"
    elif [[ "$frame" == "box" ]]; then
      printf "echo -e '"
      printf '%s╔' "${TC[1]}"
      printf "%${width}s" "" | tr ' ' '═'
      printf "╗%s'\n" "$N"
    fi
    # Logo lines, theme colors cycled
    local i line esc
    for ((i = 0; i < ${#LOGO[@]}; i++)); do
      line="${LOGO[$i]}"
      esc="$line"
      esc="${esc//\\/\\\\}"
      esc="${esc//\"/\\\"}"
      esc="${esc//\$/\\\$}"
      esc="${esc//\`/\\\`}"
      if [[ "$frame" == "box" ]]; then
        printf 'echo -e "%s║%-'"$width"'s║%s"\n' "${TC[$((i % ncols))]}" "$esc" "$N"
      else
        printf 'echo -e "%s%s%s"\n' "${TC[$((i % ncols))]}" "$esc" "$N"
      fi
    done
    # Bottom frame
    if [[ "$frame" == "line" ]]; then
      printf "echo -e '"
      printf '%s' "${TC[1]}"
      printf "%${width}s" "" | tr ' ' '─'
      printf "%s'\n" "$N"
    elif [[ "$frame" == "stars" ]]; then
      printf "echo -e '"
      printf '%s' "${TC[2 % ncols]}"
      local j; for ((j = 0; j < width; j += 2)); do printf '★ '; done
      printf "%s'\n" "$N"
    elif [[ "$frame" == "box" ]]; then
      printf "echo -e '"
      printf '%s╚' "${TC[1]}"
      printf "%${width}s" "" | tr ' ' '═'
      printf "╝%s'\n" "$N"
    fi
    echo "echo \"\""
    # Rainbow divider
    printf "echo -e '"
    local k; for ((k = 0; k < 48; k++)); do printf '%s━' "${TC[$((k % ncols))]}"; done
    printf "%s'\n" "$N"
    echo "echo \"\""
    # Name strip
    printf "echo -e '            "
    local c; for ((c = 0; c < ${#sname}; c++)); do printf '%s%s' "${TC[$((c % ncols))]}" "${sname:$c:1}"; done
    printf " %s'\n" "$N"
    echo "echo \"\""
    # Info box (date/time filled at display time)
    echo "echo -e '${TC[0]} ┌────────────────────────────────────────────────────┐${N}'"
    echo "echo -e \"${TC[0]} │\${N} ${TC[1]}👤 User    : \${W}${dname}\${N}                                   ${TC[0]}│\${N}\""
    echo "echo -e \"${TC[0]} │\${N} ${TC[2 % ncols]}📅 Date    : \${W}\$(date '+%A, %d %B %Y')\${N}                 ${TC[0]}│\${N}\""
    echo "echo -e \"${TC[0]} │\${N} ${TC[1]}⏰ Time    : \${W}\$(date '+%I:%M:%S %p')\${N}                            ${TC[0]}│\${N}\""
    echo "echo -e '${TC[0]} └────────────────────────────────────────────────────┘${N}'"
    echo "echo \"\""
    if ((width > 62)); then
      echo "echo -e '${TC[1]}  (Tip: pinch-zoom out if the logo wraps on small screens)${N}'"
      echo "echo \"\""
    fi
  } > "$BANNER_OUT"
  chmod +x "$BANNER_OUT"
}

# ═══════════════ Prompt builder ═══════════════
build_prompt_ps1() {
  local pname="$1" theme="$2"
  load_theme "$theme"
  local W='\e[1;37m' N='\e[0m'
  local tpl="${PROMPT_PS1[$pname]:-${PROMPT_PS1["FPV Arrow"]}}"
  local ps1="$tpl"
  ps1="${ps1//\{1\}/\\[${TC[0]}\\]}"
  ps1="${ps1//\{2\}/\\[${TC[1]}\\]}"
  ps1="${ps1//\{3\}/\\[${TC[2 % ${#TC[@]}]}\\]}"
  ps1="${ps1//\{W\}/\\[$W\\]}"
  ps1="${ps1//\{X\}/\\[$N\\]}"
  printf '%s' "$ps1"
}

apply_bashrc() {
  local prompt theme ps1
  prompt="$(cfg_get PROMPT)"; [[ -z "$prompt" ]] && prompt="FPV Arrow"
  theme="$(cfg_get THEME)";   [[ -z "$theme" ]] && theme="Ocean 🌊"
  ps1="$(build_prompt_ps1 "$prompt" "$theme")"

  if [[ -f "$HOME/.bashrc" ]] && ! grep -q "Termux Banner Tool" "$HOME/.bashrc" 2>/dev/null; then
    cp "$HOME/.bashrc" "$BACKUP_DIR/bashrc.backup.$(date +%s)"
  fi

  {
    echo "# Termux Banner Tool - auto generated ($(date '+%F %T'))"
    echo "# Your old .bashrc is backed up in ~/.termux-banner-tool/backups/"
    echo ""
    echo "if [ -f \"$BANNER_OUT\" ]; then"
    echo "  bash \"$BANNER_OUT\""
    echo "fi"
    echo ""
    echo "PS1='$ps1'"
  } > "$HOME/.bashrc"
}

rebuild_all() { build_banner; apply_bashrc; }

# ═══════════════ UI ═══════════════
show_header() {
  clear
  echo -e "${IC}╔══════════════════════════════════════════════════════════╗${IN}"
  echo -e "${IC}║${IW}        🎨 TERMUX BANNER TOOL v2.0 🎨                  ${IC}║${IN}"
  echo -e "${IC}║${IG}        35 banners • 35 prompts • 10 themes            ${IC}║${IN}"
  echo -e "${IC}╚══════════════════════════════════════════════════════════╝${IN}"
  echo ""
}

pause() { echo -e "  ${IY}Press Enter to continue...${IN}"; read -r _; }

select_banner() {
  show_header
  echo -e "${IW}  🎨 BANNER STYLES (35 options):${IN}"
  echo -e "${IC}  ─────────────────────────────────────────${IN}"
  local i
  for ((i = 0; i < ${#BANNER_ORDER[@]}; i++)); do
    printf "  ${IC}[%2d]${IN} %s\n" "$((i + 1))" "${BANNER_ORDER[$i]}"
  done
  echo ""
  echo -e "  ${IY}Enter number 1-${#BANNER_ORDER[@]} (0 = back): ${IN}"
  read -r choice
  [[ "$choice" == "0" ]] && return 0
  if ! [[ "$choice" =~ ^[0-9]+$ ]] || ((choice < 1 || choice > ${#BANNER_ORDER[@]})); then
    echo -e "  ${IR}Invalid choice!${IN}"; sleep 1; select_banner; return
  fi
  local style="${BANNER_ORDER[$((choice - 1))]}"
  cfg_set "BANNER" "$style"
  rebuild_all
  echo ""
  echo -e "  ${IG}Preview: $style${IN}"
  echo -e "${IC}  ─────────────────────────────────────────${IN}"
  bash "$BANNER_OUT"
  echo ""
  echo -e "  ${IY}Keep this style? (y/n): ${IN}"
  read -r yn
  if [[ "$yn" != "y" && "$yn" != "Y" ]]; then
    echo -e "  ${IY}Not saved. Pick again.${IN}"; sleep 1; select_banner; return
  fi
  echo -e "  ${IG}✅ Banner saved: $style${IN}"; sleep 1
}

preview_prompt_line() {
  local pname="$1" theme="$2"
  load_theme "$theme"
  local W='\e[1;37m' N='\e[0m'
  local tpl="${PROMPT_PS1[$pname]}"
  local s="$tpl"
  s="${s//\{1\}/${TC[0]}}"; s="${s//\{2\}/${TC[1]}}"
  s="${s//\{3\}/${TC[2 % ${#TC[@]}]}}"; s="${s//\{W\}/$W}"; s="${s//\{X\}/$N}"
  s="${s//\\w/\~\/demo}"; s="${s//\\W/demo}"; s="${s//\\u/user}"
  s="${s//\\h/termux}"; s="${s//\\t/12:00:00}"; s="${s//\\d/Thu Jan 01}"
  s="${s//\\\$/\$}"; s="${s//\\#/1}"; s="${s//\\j/0}"
  s="${s//\\n/$'\n'   }"
  echo -e "   $s${N}echo hi"
}

select_prompt() {
  show_header
  echo -e "${IW}  💻 PROMPT STYLES (35 options):${IN}"
  echo -e "${IC}  ─────────────────────────────────────────${IN}"
  local theme i
  theme="$(cfg_get THEME)"; [[ -z "$theme" ]] && theme="Ocean 🌊"
  for ((i = 0; i < ${#PROMPT_ORDER[@]}; i++)); do
    printf "  ${IC}[%2d]${IN} %s\n" "$((i + 1))" "${PROMPT_ORDER[$i]}"
    preview_prompt_line "${PROMPT_ORDER[$i]}" "$theme"
  done
  echo ""
  echo -e "  ${IY}Enter number 1-${#PROMPT_ORDER[@]} (0 = back): ${IN}"
  read -r choice
  [[ "$choice" == "0" ]] && return 0
  if ! [[ "$choice" =~ ^[0-9]+$ ]] || ((choice < 1 || choice > ${#PROMPT_ORDER[@]})); then
    echo -e "  ${IR}Invalid choice!${IN}"; sleep 1; select_prompt; return
  fi
  local style="${PROMPT_ORDER[$((choice - 1))]}"
  cfg_set "PROMPT" "$style"
  rebuild_all
  echo -e "  ${IG}✅ Prompt saved: $style${IN}"
  echo -e "  ${IY}Restart Termux (or run: source ~/.bashrc) to see it.${IN}"
  sleep 2
}

select_theme() {
  show_header
  echo -e "${IW}  🎨 COLOR THEMES (10 options):${IN}"
  echo -e "${IC}  ─────────────────────────────────────────${IN}"
  local i t c arr
  for ((i = 0; i < ${#THEME_ORDER[@]}; i++)); do
    t="${THEME_ORDER[$i]}"
    IFS='|' read -r -a arr <<< "${THEME_COLORS[$t]}"
    printf "  ${IC}[%2d]${IN} %-14s " "$((i + 1))" "$t"
    for c in "${arr[@]}"; do printf "%b███" "$c"; done
    printf "%b\n" "$IN"
  done
  echo ""
  echo -e "  ${IY}Enter number 1-${#THEME_ORDER[@]} (0 = back): ${IN}"
  read -r choice
  [[ "$choice" == "0" ]] && return 0
  if ! [[ "$choice" =~ ^[0-9]+$ ]] || ((choice < 1 || choice > ${#THEME_ORDER[@]})); then
    echo -e "  ${IR}Invalid choice!${IN}"; sleep 1; select_theme; return
  fi
  local theme="${THEME_ORDER[$((choice - 1))]}"
  cfg_set "THEME" "$theme"
  rebuild_all
  echo -e "  ${IG}✅ Theme saved: $theme${IN}"; sleep 1
}

set_name() {
  show_header
  echo -e "${IW}  ✏️  SET YOUR NAME${IN}"
  echo -e "${IC}  ─────────────────────────────────────────${IN}"
  echo ""
  echo -e "  ${IG}Current name: $(cfg_get NAME)${IN}"
  echo ""
  echo -e "  ${IY}Enter your name (0 = back): ${IN}"
  read -r name
  [[ "$name" == "0" ]] && return 0
  if [[ -z "$name" ]]; then echo -e "  ${IR}Name cannot be empty!${IN}"; sleep 1; return 0; fi
  cfg_set "NAME" "$name"
  rebuild_all
  echo -e "  ${IG}✅ Name saved: $name${IN}"; sleep 1
}

preview_setup() {
  show_header
  echo -e "${IW}  👁️  CURRENT SETUP${IN}"
  echo -e "${IC}  ─────────────────────────────────────────${IN}"
  echo -e "  ${IG}Name   : $(cfg_get NAME)${IN}"
  echo -e "  ${IG}Banner : $(cfg_get BANNER)${IN}"
  echo -e "  ${IG}Prompt : $(cfg_get PROMPT)${IN}"
  echo -e "  ${IG}Theme  : $(cfg_get THEME)${IN}"
  echo -e "${IC}  ─────────────────────────────────────────${IN}"
  bash "$BANNER_OUT"
  echo ""
  pause
}

reset_default() {
  show_header
  echo -e "${IW}  🔄 RESET TO DEFAULT${IN}"
  echo -e "${IC}  ─────────────────────────────────────────${IN}"
  echo -e "  ${IR}⚠️  This restores your original .bashrc from backup.${IN}"
  echo -e "  ${IY}Are you sure? (y/n): ${IN}"
  read -r confirm
  if [[ "$confirm" == "y" || "$confirm" == "Y" ]]; then
    do_reset_now
  else
    echo -e "  ${IY}Reset cancelled.${IN}"
  fi
  sleep 2
}

uninstall_tool() {
  show_header
  echo -e "${IW}  🗑️  UNINSTALL${IN}"
  echo -e "${IC}  ─────────────────────────────────────────${IN}"
  echo -e "  ${IR}⚠️  This removes the tool, banner and custom prompt.${IN}"
  echo -e "  ${IY}Are you sure? (y/n): ${IN}"
  read -r confirm
  if [[ "$confirm" == "y" || "$confirm" == "Y" ]]; then
    bash "$REPO_DIR/uninstall.sh"
    echo -e "  ${IG}✅ Uninstalled. Restart Termux.${IN}"
    exit 0
  else
    echo -e "  ${IY}Uninstall cancelled.${IN}"
  fi
  sleep 1
}

main_menu() {
  while true; do
    show_header
    echo -e "  ${IG}Name: $(cfg_get NAME)  •  Banner: $(cfg_get BANNER)${IN}"
    echo -e "  ${IG}Prompt: $(cfg_get PROMPT)  •  Theme: $(cfg_get THEME)${IN}"
    echo ""
    echo -e "${IG} ┌────────────────────────────────────────────────────┐${IN}"
    echo -e "${IG} │${IN} ${IC}[1]${IW} 🎨 Banner Style (35 options)${IN}                   ${IG}│${IN}"
    echo -e "${IG} │${IN} ${IC}[2]${IW} 💻 Prompt Style (35 options)${IN}                   ${IG}│${IN}"
    echo -e "${IG} │${IN} ${IC}[3]${IW} 🌈 Color Theme (10 options)${IN}                    ${IG}│${IN}"
    echo -e "${IG} │${IN} ${IC}[4]${IW} ✏️  Set Your Name${IN}                                ${IG}│${IN}"
    echo -e "${IG} │${IN} ${IC}[5]${IW} 👁️  Preview Banner${IN}                               ${IG}│${IN}"
    echo -e "${IG} │${IN} ${IC}[6]${IW} 🔄 Reset to Default${IN}                             ${IG}│${IN}"
    echo -e "${IG} │${IN} ${IC}[7]${IW} 🗑️  Uninstall${IN}                                    ${IG}│${IN}"
    echo -e "${IG} │${IN} ${IC}[8]${IW} 🚪 Exit${IN}                                         ${IG}│${IN}"
    echo -e "${IG} └────────────────────────────────────────────────────┘${IN}"
    echo ""
    echo -e "  ${IY}Select [1-8]: ${IN}"
    read -r choice
    case "$choice" in
      1) select_banner ;;
      2) select_prompt ;;
      3) select_theme ;;
      4) set_name ;;
      5) preview_setup ;;
      6) reset_default ;;
      7) uninstall_tool ;;
      8) echo -e "  ${IG}Goodbye! 👋${IN}"; exit 0 ;;
      *) echo -e "  ${IR}Invalid option!${IN}"; sleep 1 ;;
    esac
  done
}

do_reset_now() {
  local latest
  latest="$(ls -t "$BACKUP_DIR"/bashrc.backup.* 2>/dev/null | head -n 1)"
  if [[ -n "$latest" ]]; then
    cp "$latest" "$HOME/.bashrc"
    echo -e "  ${IG}✅ Original .bashrc restored from backup.${IN}"
  else
    printf '%s\n' "PS1='\\w \\$ '" > "$HOME/.bashrc"
    echo -e "  ${IG}✅ No backup found — wrote a clean default .bashrc.${IN}"
  fi
  rm -f "$CONFIG_FILE" "$BANNER_OUT"
  echo -e "  ${IG}✅ Settings cleared. Restart Termux.${IN}"
}

show_help() {
  echo -e "${IC}Termux Banner Tool v2.0${IN}"
  echo ""
  echo -e "  ${IW}Usage:${IN}"
  echo -e "    bash install.sh              Open the interactive menu"
  echo -e "    bash install.sh --install    Apply banner + prompt (no menu)"
  echo -e "    bash install.sh --reset      Restore original Termux setup"
  echo -e "    bash install.sh --uninstall  Remove the tool completely"
  echo -e "    bash install.sh --help       Show this help"
  echo -e "    bash uninstall.sh            Standalone uninstaller"
}

# ═══════════════ Start ═══════════════
check_deps
init_config
if [[ ! -f "$BANNER_OUT" ]]; then rebuild_all; fi

case "${1:-}" in
  --install)
    rebuild_all
    echo -e "  ${IG}✅ Installed! Restart Termux to see your banner.${IN}"
    exit 0 ;;
  --reset)
    do_reset_now
    exit 0 ;;
  --uninstall)
    bash "$REPO_DIR/uninstall.sh"
    exit 0 ;;
  --help|-h)
    show_help
    exit 0 ;;
  "")
    ;;
  *)
    echo -e "  ${IR}Unknown option: $1${IN}"
    show_help
    exit 1 ;;
esac
main_menu
